dependencies:
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: cleanup
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.2.0
